import {useEffect, useMemo, useState} from 'react';
import {Button as CoreButton} from '@astryxdesign/core/Button';
import {Card} from '@astryxdesign/core/Card';
import {navigateInProject} from './api/projectLocation';
import {apiErrorMessage, evoRailApi, type ApiActivity, type ApiApproval, type ApiReview, type Pagination} from './api/evoRailApi';
import {useEvoRail} from './api/EvoRailProvider';
import {useUrlSearch} from './api/m3';
import {EvoAsyncState, EvoFilterBar, EvoPageHeader, EvoRevisionBadge, EvoStatusBadge, EvoTimeline} from './components/evorail';

function Button(props: Parameters<typeof CoreButton>[0] & {disabled?: boolean}) {
  const {disabled, ...rest} = props;
  return <CoreButton {...rest} isDisabled={disabled} />;
}

function go(path: string): void { navigateInProject(path); }
function date(value?: string | null): string { return value ? new Intl.DateTimeFormat('fr-FR', {day: '2-digit', month: 'short', year: 'numeric'}).format(new Date(value)) : '—'; }
function dateTime(value?: string | null): string { return value ? new Intl.DateTimeFormat('fr-FR', {dateStyle: 'medium', timeStyle: 'short'}).format(new Date(value)) : '—'; }
function statusLabel(value?: string): string { return ({open: 'Ouvert', in_progress: 'En cours', returned: 'Retourné', completed: 'Terminé', cancelled: 'Annulé', pending: 'En attente', approved: 'Approuvé', rejected: 'Rejeté'} as Record<string, string>)[value ?? ''] ?? value ?? '—'; }
function errorText(cause: unknown): string { return apiErrorMessage(cause) || 'API indisponible.'; }
function pagination(value: Pagination | undefined): Pagination { return value ?? {total: 0, current_page: 1, last_page: 1, per_page: 25}; }

function WorkflowHeader({title, subtitle, onBack}: {title: string; subtitle: string; onBack?: () => void}) {
  return <>{onBack && <button className="text-button workflow-back" onClick={onBack}>← Retour à la file</button>}<EvoPageHeader eyebrow="WORKFLOW CONTRÔLÉ" title={title} subtitle={subtitle} /></>;
}

function ReviewRow({review}: {review: ApiReview}) {
  return <tr><td><button className="document-link" onClick={() => go(`/reviews/${review.id}`)}><span className="document-code">{review.document?.document_number ?? review.document_id}</span><span className="document-name">{review.document?.title ?? 'Document contrôlé'}</span></button></td><td><EvoRevisionBadge code={review.revision?.revision_code ?? review.revision_id} /></td><td><EvoStatusBadge status={review.status} label={statusLabel(review.status)} /></td><td>{review.assignee?.name ?? 'Non assigné'}</td><td>{date(review.due_at)}{review.due_at && new Date(review.due_at) < new Date() && !['completed', 'cancelled'].includes(review.status) && <span className="overdue-text"> · En retard</span>}</td><td>{review.document?.discipline ?? '—'}</td></tr>;
}

function ApprovalRow({approval}: {approval: ApiApproval}) {
  return <tr><td><button className="document-link" onClick={() => go(`/approvals/${approval.id}`)}><span className="document-code">{approval.document?.document_number ?? approval.document_id}</span><span className="document-name">{approval.document?.title ?? 'Document contrôlé'}</span></button></td><td><EvoRevisionBadge code={approval.revision?.revision_code ?? approval.revision_id} /></td><td><EvoStatusBadge status={approval.status} label={statusLabel(approval.status)} /></td><td>{approval.approver?.name ?? '—'}</td><td>{date(approval.requested_at)}</td><td>{approval.document?.discipline ?? '—'}</td></tr>;
}

function QueueControls({kind, params, updateUrl}: {kind: 'review' | 'approval'; params: URLSearchParams; updateUrl: (values: Record<string, string | undefined>) => void}) {
  const status = params.get('status') ?? '';
  return <EvoFilterBar><div className="register-toolbar"><label>Statut <select aria-label="Statut" value={status} onChange={event => updateUrl({status: event.target.value, page: '1'})}><option value="">Tous</option>{(kind === 'review' ? ['open', 'in_progress', 'returned', 'completed', 'cancelled'] : ['pending', 'approved', 'rejected', 'cancelled']).map(value => <option key={value} value={value}>{statusLabel(value)}</option>)}</select></label><label>Discipline <input aria-label="Discipline" value={params.get('discipline') ?? ''} onChange={event => updateUrl({discipline: event.target.value, page: '1'})} /></label><label>Document <input aria-label="Document" value={params.get('document_id') ?? ''} onChange={event => updateUrl({document_id: event.target.value, page: '1'})} /></label><label>Révision exacte <input aria-label="Révision exacte" value={params.get('revision_id') ?? ''} onChange={event => updateUrl({revision_id: event.target.value, page: '1'})} /></label>{kind === 'review' && <label><input type="checkbox" aria-label="En retard" checked={params.get('overdue') === '1'} onChange={event => updateUrl({overdue: event.target.checked ? '1' : undefined, page: '1'})} /> En retard</label>}<label>Trier <select aria-label="Trier" value={params.get('sort') ?? (kind === 'review' ? '-created_at' : '-requested_at')} onChange={event => updateUrl({sort: event.target.value, page: '1'})}>{(kind === 'review' ? ['-created_at', 'due_at', '-due_at', 'status'] : ['-requested_at', 'requested_at', 'status']).map(value => <option key={value}>{value}</option>)}</select></label></div></EvoFilterBar>;
}

export function ReviewsPage() {
  const {project} = useEvoRail();
  const [params, updateUrl] = useUrlSearch();
  const [items, setItems] = useState<ApiReview[]>([]);
  const [pageInfo, setPageInfo] = useState<Pagination>();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const query = useMemo(() => Object.fromEntries([...params.entries()].filter(([key]) => key !== 'selected')), [params.toString()]);
  useEffect(() => { let cancelled = false; if (!project) return; setLoading(true); setError(''); void evoRailApi.reviews(project.id, query).then(result => { if (!cancelled) {setItems(result.items); setPageInfo(result.pagination);} }).catch(cause => {if (!cancelled) setError(errorText(cause));}).finally(() => {if (!cancelled) setLoading(false);}); return () => {cancelled = true;}; }, [project?.id, JSON.stringify(query)]);
  const info = pagination(pageInfo);
  return <div className="page-frame register-page"><WorkflowHeader title="Avis" subtitle="Files de revue reliées à une révision exacte." /><QueueControls kind="review" params={params} updateUrl={updateUrl} />{loading && <EvoAsyncState state="loading" message="Chargement des avis…" />}{error && <EvoAsyncState state="error" message={error} />}{!loading && !error && items.length === 0 && <EvoAsyncState state="empty" message="Aucun avis correspondant." />}<Card variant="default" padding={0} className="register-card"><div className="table-shell"><table><thead><tr><th>Document</th><th>Révision</th><th>Statut</th><th>Assigné à</th><th>Échéance</th><th>Discipline</th></tr></thead><tbody>{items.map(item => <ReviewRow key={item.id} review={item} />)}</tbody></table></div><QueuePagination value={info} updateUrl={updateUrl} label="Pages des avis" /></Card></div>;
}

export function ApprovalsPage() {
  const {project} = useEvoRail();
  const [params, updateUrl] = useUrlSearch();
  const [items, setItems] = useState<ApiApproval[]>([]);
  const [pageInfo, setPageInfo] = useState<Pagination>();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const query = useMemo(() => Object.fromEntries(params.entries()), [params.toString()]);
  useEffect(() => { let cancelled = false; if (!project) return; setLoading(true); setError(''); void evoRailApi.approvals(project.id, query).then(result => {if (!cancelled) {setItems(result.items); setPageInfo(result.pagination);}}).catch(cause => {if (!cancelled) setError(errorText(cause));}).finally(() => {if (!cancelled) setLoading(false);}); return () => {cancelled = true;}; }, [project?.id, JSON.stringify(query)]);
  const info = pagination(pageInfo);
  return <div className="page-frame register-page"><WorkflowHeader title="Approbations" subtitle="Décisions finales immuablement liées à une révision exacte." /><QueueControls kind="approval" params={params} updateUrl={updateUrl} />{loading && <EvoAsyncState state="loading" message="Chargement des approbations…" />}{error && <EvoAsyncState state="error" message={error} />}{!loading && !error && items.length === 0 && <EvoAsyncState state="empty" message="Aucune approbation correspondante." />}<Card variant="default" padding={0} className="register-card"><div className="table-shell"><table><thead><tr><th>Document</th><th>Révision</th><th>Décision</th><th>Approbateur</th><th>Demandée le</th><th>Discipline</th></tr></thead><tbody>{items.map(item => <ApprovalRow key={item.id} approval={item} />)}</tbody></table></div><QueuePagination value={info} updateUrl={updateUrl} label="Pages des approbations" /></Card></div>;
}

function QueuePagination({value, updateUrl, label}: {value: Pagination; updateUrl: (values: Record<string, string | undefined>) => void; label: string}) {
  return <div className="table-footer"><span>{value.total} enregistrement(s)</span><nav className="pagination" aria-label={label}><button aria-label="Page précédente" disabled={value.current_page <= 1} onClick={() => updateUrl({page: String(value.current_page - 1)})}>←</button><button className="is-current">{value.current_page}</button><button aria-label="Page suivante" disabled={value.current_page >= value.last_page} onClick={() => updateUrl({page: String(value.current_page + 1)})}>→</button></nav></div>;
}

function Activity({items}: {items: ApiActivity[]}) { return <EvoTimeline items={items.map(item => ({id: item.id, title: item.event_type, date: dateTime(item.created_at)}))} />; }

export function ReviewDetail({id}: {id: string}) {
  const [review, setReview] = useState<ApiReview | null>(null); const [activity, setActivity] = useState<ApiActivity[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [comment, setComment] = useState(''); const [busy, setBusy] = useState(false); const [success, setSuccess] = useState('');
  const load = () => {setLoading(true); setError(''); void evoRailApi.review(id).then(result => {setReview(result.review); setActivity(result.activity);}).catch(cause => setError(errorText(cause))).finally(() => setLoading(false));};
  useEffect(() => {load();}, [id]);
  const run = async (action: 'start' | 'complete' | 'return') => {if (busy) return; setBusy(true); setError(''); try {await evoRailApi.transitionReview(id, action); setSuccess(`Avis ${statusLabel(action === 'start' ? 'in_progress' : action === 'complete' ? 'completed' : 'returned').toLowerCase()}.`); load(); window.dispatchEvent(new Event('evorail:reviews-invalidated'));} catch (cause) {setError(errorText(cause));} finally {setBusy(false);}};
  const addComment = async (event: React.FormEvent) => {event.preventDefault(); if (!comment.trim() || busy) return; setBusy(true); setError(''); try {await evoRailApi.commentReview(id, comment.trim()); setComment(''); setSuccess('Commentaire ajouté.'); load();} catch (cause) {setError(errorText(cause));} finally {setBusy(false);}};
  if (loading) return <div className="page-frame"><EvoAsyncState state="loading" message="Chargement de l’avis…" /></div>;
  if (!review) return <div className="page-frame"><Card variant="default" padding={6}><p role="alert">{error || 'Avis introuvable.'}</p><Button label="Retour" variant="secondary" size="sm" onClick={() => go('/reviews')} /></Card></div>;
  const final = ['completed', 'cancelled'].includes(review.status);
  return <div className="page-frame detail-page">{error && <div className="api-state api-error" role="alert">{error}</div>}{success && <div className="api-state" role="status">{success}</div>}<WorkflowHeader title={review.document?.document_number ?? 'Avis'} subtitle={`${review.document?.title ?? 'Document'} · Révision exacte ${review.revision?.revision_code ?? review.revision_id}`} onBack={() => go('/reviews')} /><section className="detail-grid"><div className="detail-main"><Card variant="default" padding={4}><div className="rail-status"><EvoStatusBadge status={review.status} label={statusLabel(review.status)} /><span>Révision ID: {review.revision_id}</span></div><dl className="metadata-list"><div><dt>Document</dt><dd>{review.document?.title ?? review.document_id}</dd></div><div><dt>Révision exacte</dt><dd>Rev {review.revision?.revision_code ?? review.revision_id} · {review.revision?.title ?? '—'}</dd></div><div><dt>Assigné à</dt><dd>{review.assignee?.name ?? 'Non assigné'}</dd></div><div><dt>Échéance</dt><dd>{dateTime(review.due_at)}</dd></div></dl></Card><Card variant="default" padding={4}><h2>Commentaires</h2><div className="activity-list">{(review.comments ?? []).map(item => <div className="activity-item" key={item.id}><div><strong>{item.author?.name ?? 'Utilisateur'}</strong><span>{item.body} · {dateTime(item.created_at)}</span></div></div>)}</div>{!final && <form onSubmit={addComment}><label htmlFor="review-comment">Ajouter un commentaire</label><textarea id="review-comment" value={comment} onChange={event => setComment(event.target.value)} /><Button label="Commenter" type="submit" variant="secondary" size="sm" isLoading={busy} /></form>}</Card><Card variant="default" padding={4}><h2>Historique</h2><Activity items={activity} /></Card></div><aside className="detail-rail"><Card variant="default" padding={4}><h2>Actions de revue</h2>{final ? <p>Cette revue est terminée et n’accepte plus de transition.</p> : <div className="header-actions"><Button label="Démarrer" variant="secondary" size="sm" onClick={() => void run('start')} disabled={busy || review.status === 'in_progress'} /><Button label="Terminer" variant="primary" size="sm" onClick={() => void run('complete')} disabled={busy || review.status !== 'in_progress'} /><Button label="Retourner" variant="secondary" size="sm" onClick={() => void run('return')} disabled={busy || review.status !== 'in_progress'} /></div>}</Card></aside></section></div>;
}

export function ApprovalDetail({id}: {id: string}) {
  const [approval, setApproval] = useState<ApiApproval | null>(null); const [activity, setActivity] = useState<ApiActivity[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false); const [success, setSuccess] = useState('');
  const load = () => {setLoading(true); setError(''); void evoRailApi.approval(id).then(result => {setApproval(result.approval); setActivity(result.activity);}).catch(cause => setError(errorText(cause))).finally(() => setLoading(false));};
  useEffect(() => {load();}, [id]);
  const decide = async (action: 'approve' | 'reject') => {if (busy || approval?.status !== 'pending') return; if (action === 'approve' && !window.confirm('Confirmer la décision finale d’approbation ?')) return; setBusy(true); setError(''); try {await evoRailApi.decideApproval(id, action, reason || undefined); setSuccess(action === 'approve' ? 'Approbation enregistrée.' : 'Rejet enregistré.'); load(); window.dispatchEvent(new Event('evorail:approvals-invalidated'));} catch (cause) {setError(errorText(cause));} finally {setBusy(false);}};
  if (loading) return <div className="page-frame"><EvoAsyncState state="loading" message="Chargement de l’approbation…" /></div>;
  if (!approval) return <div className="page-frame"><Card variant="default" padding={6}><p role="alert">{error || 'Approbation introuvable.'}</p><Button label="Retour" variant="secondary" size="sm" onClick={() => go('/approvals')} /></Card></div>;
  const final = approval.status !== 'pending';
  return <div className="page-frame detail-page">{error && <div className="api-state api-error" role="alert">{error}</div>}{success && <div className="api-state" role="status">{success}</div>}<WorkflowHeader title={approval.document?.document_number ?? 'Approbation'} subtitle={`${approval.document?.title ?? 'Document'} · Révision exacte ${approval.revision?.revision_code ?? approval.revision_id}`} onBack={() => go('/approvals')} /><section className="detail-grid"><div className="detail-main"><Card variant="default" padding={4}><div className="rail-status"><EvoStatusBadge status={approval.status} label={statusLabel(approval.status)} />{final && <strong>Décision finale et immuable</strong>}</div><dl className="metadata-list"><div><dt>Révision exacte</dt><dd>Rev {approval.revision?.revision_code ?? approval.revision_id} · {approval.revision?.title ?? '—'}</dd></div><div><dt>Demandée par</dt><dd>{approval.requested_by?.name ?? '—'}</dd></div><div><dt>Approbateur</dt><dd>{approval.approver?.name ?? '—'}</dd></div><div><dt>Demandée le</dt><dd>{dateTime(approval.requested_at)}</dd></div><div><dt>Décidée le</dt><dd>{dateTime(approval.decided_at)}</dd></div><div><dt>Motif</dt><dd>{approval.decision_reason || '—'}</dd></div></dl></Card><Card variant="default" padding={4}><h2>Historique</h2><Activity items={activity} /></Card></div><aside className="detail-rail"><Card variant="default" padding={4}><h2>Décision</h2>{final ? <p>Les contrôles de décision sont masqués après la décision finale.</p> : <><label htmlFor="approval-reason">Motif ou commentaire (facultatif)</label><textarea id="approval-reason" value={reason} onChange={event => setReason(event.target.value)} /><div className="header-actions"><Button label="Rejeter" variant="secondary" size="sm" onClick={() => void decide('reject')} disabled={busy} /><Button label="Approuver" variant="primary" size="sm" onClick={() => void decide('approve')} disabled={busy} /></div></>}</Card></aside></section></div>;
}

export function MyWorkPage() {
  const {project, user} = useEvoRail(); const [reviews, setReviews] = useState<ApiReview[]>([]); const [approvals, setApprovals] = useState<ApiApproval[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => {let cancelled = false; if (!project || !user) return; setLoading(true); void Promise.all([evoRailApi.reviews(project.id, {assignee_user_id: user.id, per_page: 100}), evoRailApi.approvals(project.id, {approver_user_id: user.id, status: 'pending', per_page: 100})]).then(([reviewResult, approvalResult]) => {if (!cancelled) {setReviews(reviewResult.items); setApprovals(approvalResult.items);}}).catch(cause => {if (!cancelled) setError(errorText(cause));}).finally(() => {if (!cancelled) setLoading(false);}); return () => {cancelled = true;};}, [project?.id, user?.id]);
  return <div className="page-frame register-page"><WorkflowHeader title="Mon travail" subtitle="Vos avis et approbations restent séparés par type et par décision." />{loading && <div className="api-state" role="status">Chargement de votre travail…</div>}{error && <div className="api-state api-error" role="alert">{error}</div>}<Card variant="default" padding={4}><h2>Avis assignés <span className="section-note">{reviews.length}</span></h2><div className="table-shell"><table><thead><tr><th>Type</th><th>Document</th><th>Révision exacte</th><th>Statut</th><th>Échéance</th></tr></thead><tbody>{reviews.map(item => <tr key={item.id}><td>Avis</td><td><button className="document-link" onClick={() => go(`/reviews/${item.id}`)}>{item.document?.document_number ?? item.document_id}</button></td><td>Rev {item.revision?.revision_code ?? item.revision_id}</td><td>{statusLabel(item.status)}</td><td>{date(item.due_at)}</td></tr>)}{!loading && reviews.length === 0 && <tr><td colSpan={5}>Aucun avis assigné.</td></tr>}</tbody></table></div></Card><Card variant="default" padding={4}><h2>Approbations en attente <span className="section-note">{approvals.length}</span></h2><div className="table-shell"><table><thead><tr><th>Type</th><th>Document</th><th>Révision exacte</th><th>Statut</th><th>Demandée le</th></tr></thead><tbody>{approvals.map(item => <tr key={item.id}><td>Approbation</td><td><button className="document-link" onClick={() => go(`/approvals/${item.id}`)}>{item.document?.document_number ?? item.document_id}</button></td><td>Rev {item.revision?.revision_code ?? item.revision_id}</td><td>{statusLabel(item.status)}</td><td>{date(item.requested_at)}</td></tr>)}{!loading && approvals.length === 0 && <tr><td colSpan={5}>Aucune approbation en attente.</td></tr>}</tbody></table></div></Card></div>;
}
